name: A pipeline 

on:
  push
  
env:
  BOOLEAN_TEST_1: true
  BOOLEAN_TEST_2: false

jobs:
  test-secret:
    name: lol
    runs-on: ubuntu-latest
    steps:
      - name: lol
        if: ${{ env.BOOLEAN_TEST_1 || env.BOOLEAN_TEST_2 }}
        run: echo "lol"
        
      - name: lel
        if: ${{ env.BOOLEAN_TEST_1 && env.BOOLEAN_TEST_2 }}
        run: echo "lel"
        
        
