name: A pipeline 

on:
  push
  
jobs:
  remove-settings:
    runs-on: ubuntu-latest
    name: Remove settings.xml
    steps:
      - run: rm -rf ~/.m2/settings.xml
        
#   job2:
#     name: job numero dos
#     runs-on: ubuntu-latest
#     needs: job1
#     steps:
#       - name: checkout
#         uses: actions/checkout@v3.5.2
        
#       - name: setup java
#         uses: actions/setup-java@v3
#         with:
#           distribution: 'oracle'
#           java-version: '17'
          
#       - name: run unit tests
#         run: mvn clean test
      
