name: A pipeline 

on:
  push
  
jobs:
  test-secret:
    env:
      GCP_KEY_DEV: ${{ secrets.GCP_KEY_DEV }}
    name: lol
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $GCP_KEY_DEV > lol.txt
          cat lol.txt
        
        
